### ISSUE TITLE
[BUG] combine scrape interval  for jobs which have smaller intervals

### ISSUE THREAD

**Issue by venkataanil** [kube-burner/kube-burner#538]
# Bug Description
Web-burner has jobs which run for 1 second and 3 second duration. In the log https://privatebin.corp.redhat.com/?f49569fc80dbf244#4TM5U9uwHZfGagVLczrtisDUNZ7Vjn1tzukeLJ8c3SKu we can see that there are 70 normal-service-jobs and each one is taking 1 second to finish. We also have 70 "served-service-job" and 70 "served-job" jobs, in which, each job is finishing in 3 seconds.

kube-burner iterates through each job https://github.com/cloud-bulldozer/kube-burner/blob/main/pkg/prometheus/prometheus.go#L66 and scrapes metrics.  As the jobs are finished in very short time, we are scraping frequently (with 1 and 3 intervals in above case), and we see frequent plotting in the grafana panels https://snapshots.raintank.io/dashboard/snapshot/Ld5ETlt4MCUO68uWeC4RVVqcttm6RcQ4 
Also we use "sum" metric for pod cpu/memory usage in grafana panel, and summing many of these values for 30 seconds resulting high cpu usage in panels https://grafana.rdu2.scalelab.redhat.com:3000/d/9qdKt3K4z/kube-burner-report-ocp-wrapper?orgId=1&var-Datasource=AWS+Dev+-+ripsaw-kube-burner&var-workload=&var-nodes=&var-uuid=c51fd618-ed8d-456c-bfd6-210e249e0f2c&var-master=master-0&var-worker=worker000-fc640&var-infra=&var-latencyPercentile=P99&from=1701129600000&to=1701130800000&var-sdn=&var-platform=&viewPanel=513 

Solutions:
1. We can comine a job with previous job for scraping (https://github.com/cloud-bulldozer/kube-burner/blob/main/pkg/prometheus/prometheus.go#L71 ) if the job's duration is less than 15 seconds (I think this the drfault promethous scraping interval). Then we can also combine jobs if their scraping start and end overlaps with each other.

For example if job1 taske 2 sec and job2 takes 5 sec, then we can combine these into one inside "ScrapeJobsMetrics" https://github.com/cloud-bulldozer/kube-burner/blob/main/pkg/prometheus/prometheus.go#L71 i.e scrape one time for 7 sec instead of scraping 2 times (2 sec and 5 sec).
If we get any overlap because of above combining i.e scrape1 is from 6:45:24 to 6:45:42 and scrape 2 is from 6:45:30 to 6:45:50, we can avoid overlap by scraping 6:45:24 to 6:45:50.

**Comment by rsevilla87** [comment]
I don't think this should be fixed on the kube-burner side, having a workload with 70 jobs with a duration of 1s makes no sense. These jobs should and can be consolidated into a single one, for example

The original job
```yaml
jobs:                                                       
{{ $normalLimit := mul .LIMITCOUNT .SCALE | int }}          
{{ range $val := untilStep 1 (add $normalLimit 1|int) 1 }}  
  - name: normal-service-job-{{ $val }}                     
    jobType: create                                         
    jobIterations: 1                                        
    qps: {{ $.QPS }}                                        
    burst: {{ $.BURST }}                                    
    namespacedIterations: false                             
    cleanup: false                                          
    namespace: served-ns-{{ (sub $val 1|int) }}             
    podWait: false                                          
    waitWhenFinished: false                                 
    verifyObjects: true                                     
    errorOnVerify: false                                    
    jobIterationDelay: 0s                                   
    jobPause: 0s                                            
    preLoadImages: false                                    
    objects:                                                
      - objectTemplate: node_density_pod_service_served.yml 
        replicas: 1                                         
{{ end }}                                                   
```

could be rewritten into something like

```yaml
jobs:                                                       
  - name: normal-service-job-{{ $val }}                     
    jobType: create                                         
    jobIterations: {{ mul .LIMITCOUNT .SCALE | int }}                                       
    qps: {{ $.QPS }}                                        
    burst: {{ $.BURST }}                                    
    namespacedIterations: true                             
    cleanup: false                                          
    namespace: served-ns            
    podWait: false                                          
    waitWhenFinished: false                                 
    verifyObjects: true                                     
    errorOnVerify: false                                    
    jobIterationDelay: 0s                                   
    jobPause: 0s                                            
    preLoadImages: false                                    
    objects:                                                
      - objectTemplate: node_density_pod_service_served.yml 
        replicas: 1                                         

```
