### ISSUE TITLE
[RFE] Read/GET job type 

### ISSUE THREAD

**Issue by riuvshyn** [kube-burner/kube-burner#575]
**Is your feature request related to a problem? Please describe.**
I would want to create load scenario not only for mutation requests but also simulation intensive GET load on API server.

**Describe the solution you'd like**
Add `jobType: read` to job definition.

**Describe alternatives you've considered**
Currently I have to run other tools to generate GET load on API server.

**Additional context**
could look like:
```
  - name: get-crds
    qps: 20
    burst: 20
    jobType: read
    objects:
      - kind: CustomResourceDefinition
        labelSelector: {kube-burner-job: api-intensive}
        apiVersion: apiextensions.k8s.io/v1
```
