### ISSUE TITLE
[BUG] job.name can not empty

### ISSUE THREAD

**Issue by ZhangShuaiyi** [kube-burner/kube-burner#628]
# Bug Description

## **Output of `kube-burner` version**
+ main

## **Describe the bug**

If `namespace` is not added in job spec , `config.Parse` will fail
```
time="2024-04-22 10:07:14" level=fatal msg="Config error: Namespace  name validation error: [a lowercase RFC 1123 subdomain must consist of lower case alphanumeric characters, '-' or '.', and must start and end with an alphanumeric character (e.g. 'example.com', regex used for validation is '[a-z0-9]([-a-z0-9]*[a-z0-9])?(\\.[a-z0-9]([-a-z0-9]*[a-z0-9])?)*')]" file="kube-burner.go:97"
```

## **To Reproduce**

Test cluster level resource `ClusterRole`
+ clusterrole-test.yml, without `namespace` field.
```
---yaml
global:
  gc: true
jobs:
  - name: clusterrole-test
    jobIterations: 2
    qps: 2
    burst: 2
    namespacedIterations: false
    objects:

      - objectTemplate: templates/clusterrole.yml
        replicas: 1
```
+ templates/clusterrole.yml
```yaml
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: clusterrole-test-{{.Iteration}}
rules:
- apiGroups: [""]
  resources: ["secrets"]
  verbs: ["get", "watch", "list"]
```
+ `kube-burner --log-level debug init -c clusterrole-test.yml`

## **Expected behavior**

Create clusterrole described in `templates/clusterrole.yml`.

## **Screenshots or output**

```
time="2024-04-22 10:13:10" level=fatal msg="Config error: Namespace  name validation error: [a lowercase RFC 1123 subdomain must consist of lower case alphanumeric characters, '-' or '.', and must start and end with an alphanumeric character (e.g. 'example.com', regex used for validation is '[a-z0-9]([-a-z0-9]*[a-z0-9])?(\\.[a-z0-9]([-a-z0-9]*[a-z0-9])?)*')]" file="kube-burner.go:97"
```
