### ISSUE TITLE
[RFE] Enhanced Wait Options for Kube-Burner

### ISSUE THREAD

**Issue by Mangaal** [kube-burner/kube-burner#653]
### Background

 I was trying to test the performance of ArgoCD by creating multiple ArgoCD applications, each deploying multiple deployments across multiple namespaces. I am using kube-burner to create these ArgoCD applications. Additionally, I need kube-burner to wait and capture data until each application reaches the synced state.

### Issue

When trying to utilise the create job wait options, I found that the status structure of kube-burner does not match the ArgoCD application status structure. As a result, when kube-burner decodes the application status, it results in an empty structure.

### Suggestions:

1. Wait Options for Read Jobs
I propose adding wait options to read jobs so that kube-burner can monitor deployments created by ArgoCD and capture metric data until the deployments are in the running state. Here is an example 
```
objects:
- kind: Deployment
  labelSelector: {kube-burner-job: cluster-density}
  apiVersion: apps/v1
  waitOption:
    forCondition: Ready
```
2. Enhanced Wait Options for Create Jobs
I also propose enhancing the create job wait options to support waiting for any kind of resource with a specified label. Here is an example 
```
objects:
- kind: Application
  objectTemplate: argocd/template/application.yaml
  replicas: 1  # Deploy 100 ArgoCD applications
  waitOptions:
    kind: Deployment
    labelSelector: {kube-burner-job: cluster-density}
    forCondition: Ready
```

Thank you for considering these feature requests.
