### ISSUE TITLE
[BUG] Deletion of Role/Rolebinding through kube-burner causes fatal error

### ISSUE THREAD

**Issue by abraham2512** [kube-burner/kube-burner#672]
# Bug Description
 Deletion of created Role/RoleBinding through a kube-burner job causes fatal error
 
## **Output of `kube-burner` version**
Version: 1.10.4
Git Commit: 2b0a32be8f0b3a3df2328e4aecc9da06da742666
Build Date: 2024-07-12T19:25:04Z
Go Version: go1.21.12
OS/Arch: linux amd64

## **Describe the bug**
Deleting Role/Rolebindings using kube-burner causes a fatal exit with the following error message
```
time="2024-07-23 09:33:19" level=info msg="🔥 Starting kube-burner (1.2.9@4a36d42712bd22e9308035149a3de93b33896f54) with UUID a5311366-1b07-4052-a942-a59dc20ca6ad" file="job.go:99"
time="2024-07-23 09:33:19" level=fatal msg="no matches for kind \"RoleBinding\" in group \"\"" file="delete.go:44"
```
## **To Reproduce**

1. Create a Kube-burner custom workload that uses Role/Rolebindings, such as the **kubectlapp** workload in the templates available [here](https://github.com/abraham2512/du-intensive/tree/master/templates)
2. Attempt to delete the created role/rolebindings using kube-burner using a delete job such as 
```
---
jobs:
  - name: remove-roles
    qps: 2
    burst: 2
    jobType: delete
    waitForDeletion: true
    objects:
      - kind: RoleBinding
        labelSelector: {kube-burner-job: du-workload}
      - kind: Role
        labelSelector: {kube-burner-job: du-workload}
```

## **Expected behavior**

Safe deletion of role/rolebinding objects created with a kube-burner job using a template.
Only way currently to do this is to select and delete each one tediously, such as,
```
[kni@registry du-intensive]$ oc delete -n workload rolebinding pod-reader-binding-1
rolebinding.rbac.authorization.k8s.io "pod-reader-binding-1" deleted
[kni@registry du-intensive]$ oc delete -n workload rolebinding pod-reader-binding-2
rolebinding.rbac.authorization.k8s.io "pod-reader-binding-2" deleted
```

## **Screenshots or output**

If applicable, add screenshots or kube-burner output to help explain your problem.
