### ISSUE TITLE
[RFE]Direct Support for wait Option for ArgoCD Applications in Kube-Burner

### ISSUE THREAD

**Issue by Mangaal** [kube-burner/kube-burner#691]
Background:

In the context of testing the performance of ArgoCD, I have been using kube-burner to create multiple ArgoCD applications. Each application deploys multiple resources across different namespaces. For accurate performance measurement, it's crucial that kube-burner waits for each ArgoCD application to reach the Synced state before capturing the relevant metrics.

Current Limitation:

While kube-burner supports waiting for specific conditions on child resources, it does not currently support a direct wait option for ArgoCD applications. This limitation arises because the status structure of kube-burner does not match the ArgoCD application status structure. When kube-burner attempts to decode the ArgoCD application status, it results in an empty structure, making it impossible to accurately wait for the Synced state of ArgoCD applications.

Issue #653 Context:

The recent fix/closure of issue #653 addressed the mismatch in the status structure, which now allows kube-burner to watch and wait for child resources created by ArgoCD. However, direct support for waiting on the ArgoCD application status itself is still missing.

Proposed Enhancement:

I propose adding a direct wait option for ArgoCD applications in kube-burner. This enhancement would allow users to specify that kube-burner should wait until an ArgoCD application reaches the Synced state before proceeding. This feature would be particularly useful for performance testing and monitoring, ensuring that all metrics are captured after the ArgoCD applications are fully synced.

Suggested Implementation:

Wait Option for Create Jobs: Enhance the create job wait options to support waiting directly on ArgoCD applications. An example configuration might look like this:
```
objects:
- kind: Application
  objectTemplate: argocd/template/application.yaml
  replicas: 1 
  waitOptions:
    kind: Application
    labelSelector: {app.kubernetes.io/instance: my-argocd-app}
    forCondition: Synced
```
