### ISSUE TITLE
[BUG] Out of the box cluster-density preload image throws "Init:CreateContainerError"

### ISSUE THREAD

**Issue by akrzos** [kube-burner/kube-burner#847]
# Bug Description

Ran:

```console
# kube-burner init -c cluster-density.yml
```

and observed some preload container images throwing an error

# oc get po -n preload-kube-burner 
NAME                 READY   STATUS                      RESTARTS   AGE
preload9snbs-ndf6j   0/1     Init:CreateContainerError   0          44s
preload9snbs-vfvzx   0/1     Init:CreateContainerError   0          44s

It appears the preload init container image is missing `echo`:

```
# oc get po -n preload-kube-burner preload9snbs-ndf6j -o yaml
...
  initContainerStatuses:
  - image: registry.k8s.io/pause:3.1
    imageID: ""
    lastState: {}
    name: container-0
    ready: false
    restartCount: 0
    started: false
    state:
      waiting:
        message: |
          container create failed: executable file `echo` not found in $PATH: No such file or directory
        reason: CreateContainerError
    volumeMounts:
    - mountPath: /var/run/secrets/kubernetes.io/serviceaccount
      name: kube-api-access-bwwng
      readOnly: true
      recursiveReadOnly: Disabled
  phase: Pending
  podIP: 10.131.0.28
  podIPs:
  - ip: 10.131.0.28
  qosClass: BestEffort
  startTime: "2025-04-11T19:13:32Z"
```

## **To Reproduce**

1. Click on '....'
1. Scroll down to '....'
1. See error

## **Screenshots or output**

If applicable, add screenshots or kube-burner output to help explain your problem.
