### ISSUE TITLE
[BUG] Race condition with waiting for jobs

### ISSUE THREAD

**Issue by rsevilla87** [kube-burner/kube-burner#853]
# Bug Description

## **Output of `kube-burner` version**
Seen in kube-burner-ocp 1.6.6@a7e7bf4ddd18bbe6a4799b36c8ee070b2df27291 based on github.com/kube-burner/kube-burner v1.15.1

## **Describe the bug**

There's a race condition when kube-burner waits for jobs completion, seems like the conditions array is not immediately available when the job is created.

```
time="2025-05-06 12:26:07" level=warning msg="Error evaluating jq path: [(.conditions.[] | select(.type == \"Complete\")).status]: cannot iterate over: null" file="waiters.go:284"
time="2025-05-06 12:26:08" level=warning msg="Error evaluating jq path: [(.conditions.[] | select(.type == \"Complete\")).status]: cannot iterate over: null" file="waiters.go:284"
time="2025-05-06 12:26:09" level=warning msg="Error evaluating jq path: [(.conditions.[] | select(.type == \"Complete\")).status]: cannot iterate over: null" file="waiters.go:284"
time="2025-05-06 12:26:10" level=warning msg="Error evaluating jq path: [(.conditions.[] | select(.type == \"Complete\")).status]: cannot iterate over: null" file="waiters.go:284"
time="2025-05-06 12:26:11" level=warning msg="Error evaluating jq path: [(.conditions.[] | select(.type == \"Complete\")).status]: cannot iterate over: null" file="waiters.go:284"
```

## **To Reproduce**

Hit it when running a benchmark with a job like this

```yaml
  - name: small
    namespace: kueue-scale-s
    jobIterations: 1
    namespacedIterations: false
    qps: 10
    burst: 10
    preLoadImages: false
    preLoadPeriod: 15s
    objects:

      - objectTemplate: local-queue.yml
        replicas: 1

      - objectTemplate: job.yml
        replicas: 20
        inputVars:
          kueue: "false"
          parallelism: 5
          runtime: 10s
```

and job.yml

```yaml
apiVersion: batch/v1
kind: Job
metadata:
  name: kueue-scale-{{.JobName}}-{{.Replica}}
  labels:
    group: test-job
{{ if eq .kueue true }}
  annotations:
    kueue.x-k8s.io/queue-name: kueue-scale
{{ end }}
spec:
  parallelism: {{.parallelism}}
  completions: {{.parallelism}}
  completionMode: Indexed
  template:
    spec:
      containers:
      - name: sleep
        image: gcr.io/k8s-staging-perf-tests/sleep:v0.1.0
        args:
          - {{.runtime}}
        resources:
          requests:
            cpu: "200m"
            memory: "100Mi"          
      restartPolicy: Never
```

## **Expected behavior**

Those warnings shouldn't be there
