### ISSUE TITLE
[RFE] Ability to template the kind field of a kubernetes object

### ISSUE THREAD

**Issue by akrzos** [kube-burner/kube-burner#862]
**Is your feature request related to a problem? Please describe.**

While attempting to create a single job that can create a number of CRDs and CRs with minimal number of pre-created yaml manifests, I discovered it seems not possible to have template language in the `kind` field of an object.

Example job:
```yml
---
global:
  gc: false

jobs:
- name: test-crd-cr
  jobType: create
  jobIterations: 5
  namespacedIterations: false
  cleanup: true
  podWait: false
  qps: 10
  burst: 10
  objects:
  - objectTemplate: crd.yml
    replicas: 1

  - objectTemplate: cr.yml
    replicas: 1
```

Example CRD:
```yaml
---
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: testcrds{{.Iteration}}.testcrd.example.com
spec:
  group: testcrd.example.com
  versions:
    - name: v1
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              properties:
                workload:
                  type: string
                iterations:
                  type: integer
  scope: Namespaced
  names:
    plural: testcrds{{.Iteration}}
    singular: testcrd{{.Iteration}}
    kind: TestCRD{{.Iteration}}
    shortNames:
    - tcrd{{.Iteration}}
```

Example CR:
```yaml
---
apiVersion: testcrd.example.com/v1
kind: TestCRD{{.Iteration}}
metadata:
  name: test{{.Replica}}
spec:
  workload: {{randAlphaNum .crSize}}
  iterations: {{.Iteration}}
```

and when I run with kube-burner:

```console
$ kube-burner init -c job-crd-cr.yml --log-level=debug
time="2025-05-15 09:44:41" level=info msg="🔥 Starting kube-burner (1.16.0@ee79f622d88168e20fc2cd14fd7bc12d64c998f0) with UUID a6addcf0-d93f-4d19-ab03-3d943cca53f6" file="job.go:84"
time="2025-05-15 09:44:41" level=debug msg="job.MaxWaitTimeout is zero in test-crd-cr, override by timeout: 4h0m0s" file="job.go:329"
time="2025-05-15 09:44:41" level=info msg="QPS: 10" file="job.go:340"
time="2025-05-15 09:44:41" level=info msg="Burst: 10" file="job.go:341"
time="2025-05-15 09:44:41" level=debug msg="Preparing create job: test-crd-cr" file="create.go:40"
time="2025-05-15 09:44:41" level=debug msg="Rendering template: crd.yml" file="create.go:46"
time="2025-05-15 09:44:41" level=info msg="Job test-crd-cr: 5 iterations with 1 CustomResourceDefinition replicas" file="create.go:78"
time="2025-05-15 09:44:41" level=debug msg="Rendering template: cr.yml" file="create.go:46"
time="2025-05-15 09:44:41" level=fatal msg="no matches for kind \"TestCRD\" in group \"testcrd.example.com\"" file="create.go:64"
```

**Describe the solution you'd like**

The ability to template the `kind` field

**Describe alternatives you've considered**

As an alternative, you can script out pre-creating all of the CRD manifests such that the `kind` field does not need to be templated.
