### ISSUE TITLE
[RFE] Ability to create CRs of a CRD that does not yet exist on the cluster until the job is running

### ISSUE THREAD

**Issue by akrzos** [kube-burner/kube-burner#863]
**Is your feature request related to a problem? Please describe.**

With kube-burner it is not possible to create CRDs dynamically and then create the CRs.

Example Job:

```yaml
---
global:
  gc: false

jobs:
- name: test-crd-cr
  namespace: test
  jobType: create
  jobIterations: 2
  namespacedIterations: true
  cleanup: false
  podWait: false
  qps: 10
  burst: 10
  objects:
  - objectTemplate: crd.yml
    replicas: 1

  - objectTemplate: cr0.yml
    replicas: 1

  - objectTemplate: cr1.yml
    replicas: 1
```

Example crd.yml
```yaml
---
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: testcrds{{.Iteration}}.testcrd.example.com
spec:
  group: testcrd.example.com
  versions:
    - name: v1
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              properties:
                workload:
                  type: string
                iterations:
                  type: integer
  scope: Namespaced
  names:
    plural: testcrds{{.Iteration}}
    singular: testcrd{{.Iteration}}
    kind: TestCRD{{.Iteration}}
    shortNames:
    - tcrd{{.Iteration}}
```

Example cr0.yml and cr1.yml
```yaml
---
apiVersion: testcrd.example.com/v1
kind: TestCRD0
metadata:
  name: test{{.Replica}}
spec:
  workload: {{randAlpha 5}}
  iterations: {{.Iteration}}

```

```yaml
---
apiVersion: testcrd.example.com/v1
kind: TestCRD1
metadata:
  name: test{{.Replica}}
spec:
  workload: {{randAlpha 5}}
  iterations: {{.Iteration}}

```

And when it is ran:
```console
$ kube-burner init -c job-crd-cr.yml 
time="2025-05-19 09:30:43" level=info msg="🔥 Starting kube-burner (1.16.0@ee79f622d88168e20fc2cd14fd7bc12d64c998f0) with UUID 1b07215f-a7e5-4000-bd46-ceb993752cef" file="job.go:84"
time="2025-05-19 09:30:43" level=info msg="QPS: 10" file="job.go:340"
time="2025-05-19 09:30:43" level=info msg="Burst: 10" file="job.go:341"
time="2025-05-19 09:30:44" level=info msg="Job test-crd-cr: 2 iterations with 1 CustomResourceDefinition replicas" file="create.go:78"
time="2025-05-19 09:30:44" level=fatal msg="no matches for kind \"TestCRD0\" in group \"testcrd.example.com\"" file="create.go:64"
```

**Describe the solution you'd like**

The ability for kube-burner to recognize when a job creates the CRD that the cr yaml files are defined from.

**Describe alternatives you've considered**

The current alternative here is to run two separate jobs, one in which CRDs are created on a cluster prior to the CRs being created.
